import requests
import os
import datetime
from openai import OpenAI
from readability import Document

# --- CONFIGURATION ---
API_KEY = os.environ.get("LLM_API_KEY") 
BASE_URL = os.environ.get("LLM_BASE_URL") # Change if using a different provider
MODEL_NAME = os.environ.get("LLM_MODEL_NAME")

if not API_KEY:
    raise ValueError("API Key not found! Set LLM_API_KEY in GitHub Secrets.")

client = OpenAI(api_key=API_KEY, base_url=BASE_URL)

def get_hn_top_stories(limit=5):
    """Fetches top story IDs and then their details from Hacker News."""
    print(f"📡 Fetching top {limit} stories from Hacker News...")
    try:
        top_ids = requests.get("https://hacker-news.firebaseio.com/v0/topstories.json").json()[:limit]
        stories = []
        for item_id in top_ids:
            item = requests.get(f"https://hacker-news.firebaseio.com/v0/item/{item_id}.json").json()
            if item.get('url'): 
                stories.append(item)
        return stories
    except Exception as e:
        print(f"Error fetching HN stories: {e}")
        return []

def fetch_article_content(url):
    """Downloads the article and extracts the main text body."""
    try:
        headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)'}
        response = requests.get(url, headers=headers, timeout=10)
        doc = Document(response.text)
        return doc.summary(), doc.title()
    except Exception as e:
        print(f"⚠️ Failed to fetch {url}: {e}")
        return None, None

def summarize_bilingual(title, content):
    """Asks Claude to summarize the content."""
    content_snippet = content[:12000] # Truncate to save tokens
    
    system_prompt = """
    You are an expert tech editor for a bilingual blog. 
    1. Analyze the content.
    2. Output a summary in English and Chinese.
    3. STRICTLY use Markdown formatting.
    4. Structure:
       ### [English Title]
       * Bullet point 1
       * Bullet point 2
       
       ### [Chinese Title]
       * Chinese Bullet point 1
       * Chinese Bullet point 2
    """

    user_prompt = f"Title: {title}\n\nContent HTML: {content_snippet}"

    try:
        response = client.chat.completions.create(
            model=MODEL_NAME,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0.3
        )
        return response.choices[0].message.content
    except Exception as e:
        print(f"AI Generation Error: {e}")
        return None

def save_to_markdown(summaries):
    """Saves to _posts/ folder with Jekyll Frontmatter."""
    
    today = datetime.datetime.now()
    date_filename = today.strftime("%Y-%m-%d") # Format: 2026-02-04
    display_date = today.strftime("%B %d, %Y")
    
    # Jekyll requires posts to be in a specific folder structure
    output_dir = "_posts"
    os.makedirs(output_dir, exist_ok=True)
    filename = f"{output_dir}/{date_filename}-daily-ai-digest.md"
    
    # JEKYLL FRONTMATTER (Critical for the blog to work)
    frontmatter = f"""---
layout: post
title: "Daily Tech Digest: {display_date}"
date: {date_filename}
categories: [AI, News]
tags: [HackerNews, Bilingual]
author: "AI Editor"
---

## 📅 Daily Trends / 每日动态
*Generated by AI, Curated for Developers.*

---
"""
    
    with open(filename, "w", encoding="utf-8") as f:
        f.write(frontmatter)
        for summary in summaries:
            f.write(summary + "\n\n---\n\n")
            
    print(f"✅ Successfully saved post to: {filename}")

# --- MAIN EXECUTION ---
if __name__ == "__main__":
    stories = get_hn_top_stories(limit=5)
    blog_content = []
    
    for story in stories:
        print(f"Processing: {story['title']}")
        html_content, title = fetch_article_content(story['url'])
        
        if html_content:
            summary = summarize_bilingual(title, html_content)
            if summary:
                formatted = f"{summary}\n\n**[Read Original / 阅读原文]({story['url']})**"
                blog_content.append(formatted)
            
    if blog_content:
        save_to_markdown(blog_content)